In [1]:
import numpy as np

y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [2]:
def mae(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    print("Total error:",total_error)

    mae=total_error/len(y_true)
    print("MAE:",mae)
    return mae
    

In [3]:
mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [4]:
np.abs(y_true-y_predicted)

array([0.7, 0.3, 1. , 0. , 0.5])

In [5]:
np.mean(np.abs(y_true-y_predicted))

0.5

In [6]:
def logloss(y_true,t_preducted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [7]:
logloss(y_true,y_predicted)

17.2696280766844

In [14]:
error=y_true-y_predicted
error

array([-0.7, -0.3,  1. ,  0. , -0.5])

In [15]:
square_error=error*error
square_error

array([0.49, 0.09, 1.  , 0.  , 0.25])

In [16]:
sse=0
for i in square_error:
    sse+=i
sse

1.83

In [18]:
mse=sse/len(y_true)
mse

0.366

In [21]:
np.mean(np.square(y_true-y_predicted))

0.366

In [ ]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse