In [2]:
import os
os.getcwd()

'C:\\Users\\osama'

In [35]:
os.chdir('C:/Digital Engineering/openCV/01_Image_Basics/images')

In [36]:
import cv2

In [37]:
img=cv2.imread('flemingo.jpg')

In [38]:
img.shape

(640, 640, 3)

In [39]:
#cv2.resize(img,(640,640))
cv2.imshow('flamingo',img)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [40]:
cv2.imwrite('./flamingo2.png',img)

True

## Splitting Color 

In [41]:
b,g,r=cv2.split(img)

In [42]:
b

array([[188, 189, 189, ..., 188, 188, 188],
       [188, 189, 189, ..., 188, 188, 188],
       [188, 189, 189, ..., 188, 188, 188],
       ...,
       [167, 167, 167, ..., 177, 177, 177],
       [171, 171, 172, ..., 177, 177, 177],
       [177, 177, 178, ..., 177, 177, 177]], dtype=uint8)

In [43]:
g

array([[163, 164, 164, ..., 163, 163, 163],
       [163, 164, 164, ..., 163, 163, 163],
       [163, 164, 164, ..., 163, 163, 163],
       ...,
       [134, 134, 134, ..., 144, 144, 144],
       [141, 141, 142, ..., 144, 144, 144],
       [147, 147, 148, ..., 144, 144, 144]], dtype=uint8)

In [46]:
cv2.imshow('color',img)
cv2.imshow('blue',b)
cv2.imshow('green',g)
cv2.imshow('red',r)
cv2.waitKey(10000)
cv2.destroyAllWindows()

## Color Converter

In [54]:
img_rgb=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [55]:
#gray scale
img_gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [56]:
cv2.imshow("bgr",img)
cv2.imshow("rgb",img_rgb)
cv2.imshow("gray",img_gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [58]:
cv2.imwrite('Gray.png',img_gray)

True

## Accessing and Manipulating images

In [59]:
import numpy as np
import cv2

In [60]:
img=cv2.imread('./bird.jpg')

In [61]:
def display(winname,image):
    cv2.imshow(winname,image)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [62]:
display('winname',img)

In [63]:
img

array([[[ 88, 188, 253],
        [ 88, 188, 253],
        [ 88, 188, 253],
        ...,
        [ 45, 137, 214],
        [ 45, 137, 214],
        [ 44, 136, 213]],

       [[ 88, 188, 253],
        [ 88, 188, 253],
        [ 88, 188, 253],
        ...,
        [ 45, 137, 214],
        [ 45, 137, 214],
        [ 45, 137, 214]],

       [[ 88, 188, 253],
        [ 88, 188, 253],
        [ 88, 188, 253],
        ...,
        [ 46, 138, 215],
        [ 45, 137, 214],
        [ 45, 137, 214]],

       ...,

       [[ 73, 170, 226],
        [ 72, 169, 225],
        [ 70, 170, 225],
        ...,
        [  1,  36,  50],
        [ 29,  77,  95],
        [ 67, 120, 140]],

       [[ 73, 170, 226],
        [ 73, 170, 226],
        [ 70, 170, 225],
        ...,
        [  0,  32,  46],
        [ 11,  61,  81],
        [ 29,  83, 106]],

       [[ 75, 172, 228],
        [ 73, 170, 226],
        [ 72, 170, 224],
        ...,
        [  0,  33,  50],
        [  2,  51,  77],
        [ 94, 148, 178]]

In [64]:
type(img)

numpy.ndarray

In [65]:
# access first 100 rows and first 100 columns
corner=img[0:100,0:100]

In [66]:
display('corner',corner)

In [69]:
# change first 100 rows and first 100 columns to green
red=(0,0,255)
img[0:100,0:100]=red

In [70]:
display('redcorner',img)

## Drawing a line

In [1]:
import numpy as np
import cv2

In [3]:
canvas=np.zeros((300,300,3),dtype='uint8')

In [4]:
def display(winname,image):
    cv2.imshow(winname, image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [5]:
display('canvas',canvas)

In [6]:
green=(0,255,0)
cv2.line(canvas,(0,0),(300,300),green)
display('canvas',canvas)

In [8]:
red=(0,0,255)
cv2.line(canvas,(300,0),(0,300),red,5)
display('canvas',canvas)

## drawing rectangle

In [9]:
cv2.rectangle(canvas,(10,10),(60,60),green)
display('canvas',canvas)

In [10]:
cv2.rectangle(canvas,(50,200),(200,225),red,5)
display('canvas',canvas)

In [12]:
blue=(255,0,0)
cv2.rectangle(canvas,(200,50),(225,200),blue,-1)
display('canvas',canvas)

## drawing circles

In [13]:
canvas=np.zeros((300,300,3),dtype='uint8')

In [17]:
centerx,centery=(canvas.shape[1]//2,canvas.shape[0]//2)

In [19]:
white=(255,255,255)
for r in range (0,175,25):
    cv2.circle(canvas,(centerx,centery),r,white)
display('canvas',canvas)

## abstract drawing

In [32]:
for i in range(0,25):
    
    radius=np.random.randint(5,200)
    color=np.random.randint(0,256,size=(3,)).tolist()
    pt= np.random.randint(0,300,size=(2,))
    
    cv2.circle(canvas,tuple(pt),radius,color,-1)
    
    
display('canvas',canvas)

In [34]:
cv2.imwrite('canvas.png',canvas)

True

# Working in Videos

In [3]:
import os
os.chdir('C:/Digital Engineering/openCV/03_Working_on_Videos/data')


In [13]:
import numpy as np
import cv2
import time

In [14]:
cap=cv2.VideoCapture('./clip.mp4')

In [17]:
fps=0

while True:
    start_time=time.time() #start time
    ret,frame=cap.read()
    
    cv2.putText(frame,'FPS: {:.0f}'.format(fps),(30,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),1)
    if ret== False:
        break
    cv2.imshow('video',frame)
    if cv2.waitKey(41)== ord('q'):
        break
    time_take=start_time-time.time() #time taken
    
    fps=1/time_take  #frame per second
    
cap.release()
cv2.destroyAllWindows()
    

## Accessing Web Caemra

In [18]:
import numpy as np
import cv2
import time

In [24]:
cap=cv2.VideoCapture(0) # 0,1,2,......
#cap1=cv2.VideoCapture(0)
fps=0

In [25]:
while True:
    start_time=time.time() #start time
    ret,frame=cap.read()
    #ret,frame1=cap1.read()
    
    cv2.putText(frame,'FPS: {:.0f}'.format(fps),(30,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),1)
   # cv2.putText(frame1,'FPS: {:.0f}'.format(fps),(30,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),1)
    if ret== False:
        break
    cv2.imshow('video',frame)
    #cv2.imshow('camera1',frame1)
    
    if cv2.waitKey(1)== ord('q'):
        break
    time_take=start_time-time.time() #time taken
    
    fps=1/time_take  #frame per second
    
cap.release()
cv2.destroyAllWindows()